from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
    url(r'^salestracker/regist/$', views.user_regist, name='user_regist'),
    url(r'^salestracker/testapi/$', views.user_regist, name='user_regist'),
	url(r'^salestracker/checkphone/$', views.checkphone, name='checkphone'),
	url(r'^salestracker/getuserlocation/$', views.getuserlocation, name='getuserlocation'),
	url(r'^salestracker/getuserlocationbycity/$', views.getuserlocationbycity, name='getuserlocationbycity'),
	url(r'^salestracker/getuserlocationbystate/$', views.getuserlocationbystate, name='getuserlocationbystate'),
	url(r'^salestracker/getuserlocationbycountry/$', views.getuserlocationbycountry, name='getuserlocationbycountry'),
	url(r'^salestracker/getuserlocationbycityandphone/$', views.getuserlocationbycityandphone, name='getuserlocationbycityandphone'),
	url(r'^salestracker/getuserlocationbystateandphone/$', views.getuserlocationbystateandphone, name='getuserlocationbystateandphone'),
	url(r'^salestracker/getuserlocationbycountryandphone/$', views.getuserlocationbycountryandphone, name='getuserlocationbycountryandphone'),
	url(r'^salestracker/saveuserlocation/$', views.saveuserlocation, name='saveuserlocation'),
	url(r'^salestracker/getallusers/$', views.getallusers, name='getallusers'),
	url(r'^salestracker/getalllocations/$', views.getalllocations, name='getalllocations'),
	url(r'^salestracker/removeuserbyphonenumber/$', views.removeuserbyphonenumber, name='removeuserbyphonenumber'),
	url(r'^salestracker/removeuserlocationbyphonenumber/$', views.removeuserlocationbyphonenumber, name='removeuserlocationbyphonenumber'),
	url(r'^salestracker/getalllocationsforcurrentday/$', views.getalllocationsforcurrentday, name='getalllocationsforcurrentday'),
	url(r'^salestracker/savedriverroute/$', views.savedriverroute, name='savedriverroute'),
	url(r'^salestracker/deletedriverroute/$', views.deletedriverroute, name='deletedriverroute'),
	url(r'^salestracker/getdriverroute/$', views.getdriverroute, name='getdriverroute'),
	url(r'^salestracker/getalldriverroute/$', views.getalldriverroute, name='getalldriverroute'),
]
